#image: gitpod/workspace-yugabytedb-preview
image:
  file: .gitpod.ybdb

tasks:
  - name: 1a-ybdb
    env:
      YB_BIN_PATH: /usr/local/yugabyte/bin
      HOST_LB: 127.0.0.1
      HOST_LB2: 127.0.0.2
      HOST_LB3: 127.0.0.3
    before: |
      mkdir -p "${GITPOD_REPO_ROOT}/ybdb/certs"
      sed -i.bak '/args.certs_path/ s/^/# /' ${YB_BIN_PATH}/yugabyted
    init: |
      yugabyted cert generate_server_certs --hostname ${HOST_LB},${HOST_LB2},${HOST_LB3} --base_dir=${GITPOD_REPO_ROOT}/ybdb/certs
    command: |
      yugabyted start --base_dir=${GITPOD_REPO_ROOT}/ybdb/ybd1 --advertise_address=$HOST_LB --tserver_flags=ysql_hba_conf_csv='{hostssl all all all md5}' --secure --certs_dir=${GITPOD_REPO_ROOT}/ybdb/certs/generated_certs/${HOST_LB}/
      yugabyted start --base_dir=${GITPOD_REPO_ROOT}/ybdb/ybd2 --advertise_address=$HOST_LB2 --join=$HOST_LB --tserver_flags=ysql_hba_conf_csv='{hostssl all all all md5}' --secure --certs_dir=${GITPOD_REPO_ROOT}/ybdb/certs/generated_certs/${HOST_LB2}/
      yugabyted start --base_dir=${GITPOD_REPO_ROOT}/ybdb/ybd3 --advertise_address=$HOST_LB3 --join=$HOST_LB --tserver_flags=ysql_hba_conf_csv='{hostssl all all all md5}' --secure --certs_dir=${GITPOD_REPO_ROOT}/ybdb/certs/generated_certs/${HOST_LB3}/
      gp await-port 5433
      sleep 5
      export PGPASSWORD="$(yugabyted status --base_dir=${GITPOD_REPO_ROOT}/ybdb/ybd1 | grep -o 'password=[^&]*' | sed 's/password=//' | sed 's/\s*|//')"
      ysqlsh "sslmode=verify-ca sslrootcert=${GITPOD_REPO_ROOT}/ybdb/certs/generated_certs/root-ca/ca.crt"

  - name: 2a-vault-init
    init: |
      wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
      echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
      sudo apt update && sudo apt install vault
    command: |
      vault server --dev --dev-root-token-id="00000000-0000-0000-0000-000000000000"
  - name: 2b-vault-ops
    env:
      VAULT_ADDR: http://127.0.0.1:8200
      VAULT_TOKEN: 00000000-0000-0000-0000-000000000000
    command: |
      gp await-port 5433 && gp await-port 8201
      rootca="$(cat ${GITPOD_REPO_ROOT}/ybdb/certs/generated_certs/root-ca/ca.crt | base64 -w 0)"
      password="$(yugabyted status --base_dir=${GITPOD_REPO_ROOT}/ybdb/ybd1 | grep -o 'password=[^&]*' | sed 's/password=//' | sed 's/\s*|//')"
      vault kv put secret/ybdb-vault ybdb-username=yugabyte ybdb-password="${password}" ybdb-root-cert="${rootca}"
      gp sync-done vault-ops

  - name: 3a-spring-boot
    init: |
      echo y | sdk install java 17.0.7-librca || true
      mvn -Denv.scp=vault -DskipTests clean package
    command: |
      gp await-port 5433 && gp sync-await vault-ops
      java -jar -Dspring.profiles.active=vault ./target/sealedsecret-1.0.jar

# exposed ports
ports:
  - port: 8080
    name: spring-boot
    onOpen: ignore
  - port: 7000
    name: yb-master-web
    onOpen: ignore
  - port: 9000
    name: yb-tserver-web
    onOpen: ignore
  - port: 7100
    name: yb-master-rpc
    onOpen: ignore
  - port: 9100
    name: yb-tserver-rpc
    onOpen: ignore
  - port: 5433
    name: ysql
    onOpen: ignore
  - port: 13000
    name: ysql-api
    onOpen: ignore
  - port: 9042
    name: ycql
    onOpen: ignore
  - port: 12000
    name: ycql-api
    onOpen: ignore
  - port: 8200
    name: vault-web
    onOpen: ignore
  - port: 8201
    name: vault-api
    onOpen: ignore
  - port: 15433
    name: yugabyted-ui
    onOpen: ignore
